// Mocks generated by Mockito 5.1.0 from annotations
// in doguinhos/test/controllers/doguinhos_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:doguinhos/models/doguinhos_model.dart' as _i2;
import 'package:doguinhos/services/doguinhos_service.dart' as _i3;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDoguinhosModel_0 extends _i1.Fake implements _i2.DoguinhosModel {}

/// A class which mocks [DoguinhosService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoguinhosService extends _i1.Mock implements _i3.DoguinhosService {
  MockDoguinhosService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url =>
      (super.noSuchMethod(Invocation.getter(#url), returnValue: '') as String);
  @override
  _i4.Future<_i2.DoguinhosModel> fetchDoguinhos([_i5.Client? client]) =>
      (super.noSuchMethod(Invocation.method(#fetchDoguinhos, [client]),
              returnValue:
                  Future<_i2.DoguinhosModel>.value(_FakeDoguinhosModel_0()))
          as _i4.Future<_i2.DoguinhosModel>);
}
